version: "3"

services:

  postgres:
    image: postgres:latest
    env_file: .env
    restart: unless-stopped
    volumes:
      - /data/prequelmemes_bot/postgres:/var/lib/postgres/data

  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - postgres

  app:
    build: .
    env_file: .env
    restart: unless-stopped
    volumes:
      - ./src:/app/src
    depends_on:
      - postgres
