version: "3"

services:

  postgres:
    image: postgres:10.4
    env_file: .env
    restart: unless-stopped
    volumes:
      - /data/prequelmemes_bot/postgres:/var/lib/postgres/data

  app:
    build: .
    env_file: .env
    restart: unless-stopped
    volumes:
      - ./src:/app/src
    depends_on:
      - postgres
